name: Deploy to WordPress.org
on:
    push:
        tags:
            - '**'
jobs:
    tag:
        name: New tag
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  coverage: none
                  tools: composer

            - name: Setup Node
              uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer vendor directory
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install PHP Dependencies
              run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader --no-interaction

            - name: Install dependencies
              run: npm ci

            - name: Build plugin
              run: npm run build

            - name: WordPress Plugin Deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              env:
                  SLUG: ${{ secrets.SLUG }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
